### ISSUE TITLE
Is shifting really necessary?

### ISSUE THREAD

**Issue by Hprairie** [goombalab/hydra#2]
Thanks for the great work. 

In the paper, you state that your formulation of directionality is just simply the following.

$$QS(\mathbf{X})=shift(SS(\mathbf{X}))+flip(shift(SS(flip(\mathbf{X}))))+\mathbf{DX}$$

Writing it like this is a quasisemiseperable matrix, however, I am wondering if the shift is really necessary. If we were to do the standard addition of two $SSM$ operations then we would end up with the matrix displayed in Figure 2.c . However, by simply adding a skip connect, i.e. $D u_t $, which is common in the mamba architecture, then we would still end up with a quasisemiseperable matrix. 

My question is then, is the shifting really necessary or could we get the same results with the following?

$$QS(\mathbf{X})= SS(\mathbf{X}) + flip(SS(flip(\mathbf{X})))+\mathbf{DX}$$

**Comment by sukjunhwang** [comment]
Great catch :)
As you mentioned, your suggestion is also a QS matrix (and the simple addition without DX is also a QS matrix).
In a high-level, shift operation can be understood as utilizing the flexibility of QS, making the diagonal not be influenced by b and c (Sec 3.2.).
We have actually tried with&without shift, and shift operation does improve Hydra's performance.

**Comment by Hprairie** [comment]
Thanks for the response, and that's super interesting that it improves its performance.
