### ISSUE TITLE
Structure of the QuasiSemiseperable Matrices

### ISSUE THREAD

**Issue by Hprairie** [goombalab/hydra#3]
Hi sorry to bother you again, but after reading through the paper a couple of times, I am really confused about the structure of the quasisemiseperable matrices. First off, from a quick glance the structure of the addition of two separate I think should be something like this.

$$ 
\begin{equation}
m_{ij} = 
\begin{cases}
    c_i^T A_{i:j} b_j & \text{for }~~ i > j \\
    2 (c_i^T b_i ) & \text{for }~~ i = j \\
    c_i^T A_{j:i} b_j & \text{for }~~ i > j \\
\end{cases}
\end{equation}
$$

However, based on figure 2.c then it appears to be something like this.

$$ 
\begin{equation}
m_{ij} = 
\begin{cases}
    c_i^T A_{i:j} b_j & \text{for }~~ i > j \\
    2 (c_i^T b_i ) & \text{for }~~ i = j \\
    c_j^T A_{j:i} b_i & \text{for }~~ i > j \\
\end{cases}
\end{equation}
$$

At least to me this doesn't make sense as this then doesn't follow the dynamics of a SSM recurrence, i.e. $c$ should be consistent across each row $i$ and $b$ should be consistent across each column $j$ of the dual matrix form. Let me know if I am wrong, but if not then, shouldn't Propisiton 3.7 not be consistent with equation 3?

Thanks for the great work and the help!

**Comment by sukjunhwang** [comment]
Ah thank you for pointing this out! We probably made a mistake on that. Yes, as you said, although the figure of the QS matrix in Fig. 2 (b) is still QS due to the definition by the rank characterization, it should be adjusted to be consistent with Hydra. We will fix this part for the next revision. Thanks a lot!

**Comment by Hprairie** [comment]
Np, though I think I should clarify. Figure 2b is what is actually confusing me. From this figure I get the same equation as shown in the paper (Equation 3). However I am confused why this equation and the figure don't appear to represent a reverse SSM scan. For example, in the equations I put here, the second one is consistent with the figures in the paper and with what is expressed in equation 3. However, I'm a little confused as to why the recurrent structure is set to be this way instead of what I put in my first equation. 

I would expect the upper triangle of the quasisemiseperable matrix to reflect the recurrent relationship along the following lines:

$$ x_t = A x_{t+1} + B_t u_t $$

$$ y_t = C_t x_t $$

However this isn't what is represent in the figures or the equations in the paper. Let me know if there is something I am missing.

**Comment by sukjunhwang** [comment]
To specify, what we should revise are both the figure and the equation. For the addition version, corrected equation would be
```math
\begin{equation}
m_{ij} = 
\begin{cases}
    c_i^T A_{i:j} b_j & \text{if } i > j \\
    2 (c_i^T b_i ) & \text{if } i = j \\
    c_i^T A_{i:j} b_j & \text{if } i < j \\
\end{cases}
\end{equation}
```

where

```math
\begin{equation}
A^{\times}_{i:j} =
\begin{cases}
    \prod_{k=j+1}^{i} A_{k} & \text{for } i > j\\
    1 & \text{for } i = j\\
    \prod_{k=i}^{j-1} A_{k} & \text{for } i < j\\
\end{cases}
\end{equation}
```

This modification would be consistent with proposition 3.7.

**Comment by sukjunhwang** [comment]
I have made changes to the [blogposts](https://goombalab.github.io/blog/2024/hydra-part1-matrix-mixer/) accordingly. You can probably check the corrections if visit the blog in incognito mode.

**Comment by Hprairie** [comment]
Thanks this makes a lot more sense!

**Comment by sukjunhwang** [comment]
Thank you for catching the mistakes 😄
