### ISSUE TITLE
Troughput and Memory Metrics

### ISSUE THREAD

**Issue by n1o** [goombalab/hydra#4]
Hey Authors,

first of I really like you work, however what I miss are the Memory and Troughput comparisons between Hydra, Vanilla BERT and M2. I was wondering If you could share them, or If you do not have them (or cannot share them) could you at least provide a hint what to expect? It is more similar to BERT or way faster and efficient like M2 or even better?

Appreciated :)

**Comment by sukjunhwang** [comment]
Hi @n1o. As BERT and M2 has dedicated kernels (e.g., Flash Attention), they show faster training throughput for short sequences although Hydra has the better complexity of O(L). However, Hydra can definitely be faster when it comes to significantly long sequences :)

**Comment by n1o** [comment]
> Hi @n1o. As BERT and M2 has dedicated kernels (e.g., Flash Attention), they show faster training throughput for short sequences although Hydra has the better complexity of O(L). However, Hydra can definitely be faster when it comes to significantly long sequences :)

Thank you :)

**Comment by n1o** [comment]
@sukjunhwang Thank you!
